### ISSUE TITLE
Update Contributors Section Link in README.md

### ISSUE THREAD

**Issue by rahulgithub-web** [namansharma3007/PollQ#15]
The `README.md` file contains a section showcasing the contributors with a broken link. The current link in the contributors' section points to different url

**Comment by rahulgithub-web** [comment]
@namansharma3007 Please assign this task and add all the required label related to `hacktoberfest`

**Comment by namansharma3007** [comment]
@rahulgithub-web Thanks for the input. It has been resolved.

**Comment by namansharma3007** [comment]
@rahulgithub-web Thanks for the input. It has been resolved.

**Comment by rahulgithub-web** [comment]
@namansharma3007 Great. Thanks for the update
