### ISSUE TITLE
Feature: Develop Result page. Multiple Developers Required.

### ISSUE THREAD

**Issue by namansharma3007** [namansharma3007/PollQ#16]
#### Develop:
   - Poll Result page
   - Should be a beautiful form

 **Shake up your brain with some ideas** 🧠

**Mission PollQ** 🚀

**Comment by NischalPaliwal** [comment]
I want to work on this and will try my way best

**Comment by ArjunMal1311** [comment]
I have revamped the design of the project
![image](https://github.com/user-attachments/assets/e4382267-1307-4725-8555-52dafc37a98c)
![image](https://github.com/user-attachments/assets/46a9e1f9-673c-40ac-9758-4a1d01d7f746)
![image](https://github.com/user-attachments/assets/5bb82400-1083-41fe-9323-cea1e2b8f8ac)
![image](https://github.com/user-attachments/assets/8ca56a4b-40f5-4bc1-a9c3-c6bedbf14049)
![image](https://github.com/user-attachments/assets/324caf7a-72b9-48d6-ae20-fc9e72e2d53a)
![image](https://github.com/user-attachments/assets/c608ca91-0e7f-4344-88ef-a24d6fd48a7c)

I want to contribute to the project

**Comment by NischalPaliwal** [comment]
![Screenshot 2024-10-03 191917](https://github.com/user-attachments/assets/874943bb-aa9a-4e77-a0a0-a0fa04b0a1bd)
Is this all right for the project? Please give suggestions.

**Comment by NischalPaliwal** [comment]
So that I can create the PR.

**Comment by namansharma3007** [comment]
> ![Screenshot 2024-10-03 191917](https://private-user-images.githubusercontent.com/156404171/373278426-874943bb-aa9a-4e77-a0a0-a0fa04b0a1bd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc5NjM4MDUsIm5iZiI6MTcyNzk2MzUwNSwicGF0aCI6Ii8xNTY0MDQxNzEvMzczMjc4NDI2LTg3NDk0M2JiLWFhOWEtNGU3Ny1hMGEwLWEwZmEwNGIwYTFiZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwM1QxMzUxNDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NjZmYjRlYzExMGE5OGFjMGNiZDkzM2U0MzUyNzk0NjY0MjdmNDdiMTFhNGMxYmViYjM4YjNlZDRjNjJlYjQ5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.wpVtf853INJN_-F5J6UVMNBgt1nZxECLwx_9nJhNZWw) Is this all right for the project? Please give suggestions.

@NischalPaliwal please make it in only 2 colors

**Comment by NischalPaliwal** [comment]
Sure @namansharma3007

**Comment by namansharma3007** [comment]
> Sure @namansharma3007

I loved your designs. Please make blue as complimentary color rather than violet.

**Comment by NischalPaliwal** [comment]
![Screenshot 2024-10-03 204229](https://github.com/user-attachments/assets/95d3d405-93bf-46d6-a16e-252b68506fe5)
please check this one

**Comment by namansharma3007** [comment]
> ![Screenshot 2024-10-03 204229](https://private-user-images.githubusercontent.com/156404171/373310111-95d3d405-93bf-46d6-a16e-252b68506fe5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc5Njg3NDMsIm5iZiI6MTcyNzk2ODQ0MywicGF0aCI6Ii8xNTY0MDQxNzEvMzczMzEwMTExLTk1ZDNkNDA1LTkzYmYtNDZkNi1hMTZlLTI1MmI2ODUwNmZlNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwM1QxNTE0MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YjU5ZGFmNTU3MGM2YmVlMjMyODJlNzA1ZDIyZjBiNTNjNjU4MWY5NGUwYzZiY2ZjMmFlYTUzNGIxMjBjYjY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.EQSV7uSkMSMtufY9IJgYljpVNA2raW75G8F0GJ-nBCA) please check this one

Can you make it with alternate. Even position: dark, Odd position: light

**Comment by NischalPaliwal** [comment]
ok

**Comment by NischalPaliwal** [comment]
![Screenshot 2024-10-03 210234](https://github.com/user-attachments/assets/74a7f1aa-0b04-4fb6-aaf6-69650640f9f8)
I think I am pretty much close to what we are expecting

**Comment by namansharma3007** [comment]
> ![Screenshot 2024-10-03 210234](https://private-user-images.githubusercontent.com/156404171/373317297-74a7f1aa-0b04-4fb6-aaf6-69650640f9f8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc5NzA4NjYsIm5iZiI6MTcyNzk3MDU2NiwicGF0aCI6Ii8xNTY0MDQxNzEvMzczMzE3Mjk3LTc0YTdmMWFhLTBiMDQtNGZiNi1hYWY2LTY5NjUwNjQwZjlmOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwM1QxNTQ5MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YjhlODNkOTg4NzQyMDQ5ZGNkOThkODgzYWRiMWExZWIwMTAwYjc0M2FjMDM3MGIwZDI4NTczMDBkYzc1YTMzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.qbIS7TEXtrQ6LEo1_8n_t0pxn2YRT_1h2SBZ-nbdJn4) I think I am pretty much close to what we are expecting

Yes You are doing great. Please make White and Gray. (Make sure they are complimentary)

**Comment by NischalPaliwal** [comment]
@namansharma3007  pull request #45 solves this one!!

**Comment by namansharma3007** [comment]
Done @NischalPaliwal

**Comment by namansharma3007** [comment]
Completed
