### ISSUE TITLE
Enhance the README.md File for Improved Clarity and Usability

### ISSUE THREAD

**Issue by rahulgithub-web** [namansharma3007/PollQ#2]
## Enhance the README.md File for Improved Clarity and Usability

The current `README.md` file can be enhanced to provide more clarity and a better user experience. The following improvements are suggested:

## Related Issues

1. **Add a Detailed Project Description:** Provide a clear description of what the PollQ project is and its purpose.
2. **Prerequisites Section:** Include a section that lists the required tools (Node.js, npm, etc.) before installing the project.
3. **Table of Contents:** Add a table of contents to make the `README.md` more navigable.
4. **Usage Instructions:** Provide detailed steps on how to use the app after installation.
5. **Contribution Guidelines:** Include clear instructions for contributors, especially for Hacktoberfest.
6. **Add Screenshots/GIFs:** Add images or GIFs showing the application interface to give users a visual overview.
7. **Badges:** Add more badges for license, repo size, stars, Hacktoberfest participation, etc.
8. **Acknowledgments:** Expand the acknowledgments section to include the libraries and frameworks used.

Please label this issue with the following tags:
- `hacktoberfest`
- `hacktoberfest2024`
- `hacktoberfest-accepted`
- `documentation`

**Comment by rahulgithub-web** [comment]
Hey @namansharma3007 Please assign this task to me and attach labels to it as mentioned above.

**Comment by rahulgithub-web** [comment]
Hey @namansharma3007 I kindly request you to add the following labels: `hacktoberfest` `hacktoberfest2024` `hacktoberfest-accepted` `documentation` Thank you!

**Comment by rahulgithub-web** [comment]
@namansharma3007 please verify the changes and merge the code

**Comment by namansharma3007** [comment]
> @namansharma3007 please verify the changes and merge the code

Hey, buddy can you create Contributing.md for this repo. As I can See you have mentioned it in the README.md. Please create it as well. Then raise an PR. So that whatever is there in the README.md works as you have mentioned.
@rahulgithub-web

**Comment by rahulgithub-web** [comment]
Hey @namansharma3007, I've created the Contributing.md file as requested and raised a PR. Now everything mentioned in the README.md should work as expected. Let me know if anything else is needed!
