### ISSUE TITLE
Side navigation bar hiding the visible page

### ISSUE THREAD

**Issue by NischalPaliwal** [namansharma3007/PollQ#29]
![Screenshot 2024-10-03 184507](https://github.com/user-attachments/assets/8baefcb9-94af-4fcb-8f37-7443193fc265)
This is how it looks currently!

**Comment by shawaiz-khan** [comment]
I will work on it

**Comment by Hiteshsambhani1** [comment]
can you assign me this work

**Comment by NischalPaliwal** [comment]
![Screenshot 2024-10-04 154803](https://github.com/user-attachments/assets/e83902be-f21e-411d-a659-56478263ae37)
![Screenshot 2024-10-04 154831](https://github.com/user-attachments/assets/3cb52b95-baab-4225-9ba4-2bf7cd91d74d)
Problem Solved !!

**Comment by NischalPaliwal** [comment]
@namansharma3007 check this out

**Comment by namansharma3007** [comment]
> @namansharma3007 check this out

Great please raise an PR

**Comment by NischalPaliwal** [comment]
@namansharma3007 raised! please look on to it
