### ISSUE TITLE
Feature: Design schema for database using MongoDB

### ISSUE THREAD

**Issue by namansharma3007** [namansharma3007/PollQ#3]
- Refer #1 for app details.

- Develop App schema according to it using mongoDB.

- Schema must de designed in ```/backend-server/models```.
    - Create folder ```models``` inside backend-server folder. Design individual files for each individual component.

**Comment by thefuadeniola** [comment]
I would like to work on creating the mongo db connection, and initializing the models. This will provide direction to make create-poll page. Please assign to me

**Comment by namansharma3007** [comment]
@thefuadeniola 
Done 
# Get on with the mission 🚀

**Comment by rahulgithub-web** [comment]
Hey @namansharma3007 , I would like to suggest creating models for the signup feature and recommend setting up a models folder under the src directory. The intended path would be /backend-server/src/models. Could you please assign this task to me?
