### ISSUE TITLE
Contact us Page

### ISSUE THREAD

**Issue by Riddhi050803** [namansharma3007/PollQ#37]
![image](https://github.com/user-attachments/assets/f6bdcefa-a7bf-42e9-a2c5-c83da3062487)
I can develop a similar Contact Us page according to the theme of this project.

**Comment by Riddhi050803** [comment]
Please assign it to me. @namansharma3007

**Comment by namansharma3007** [comment]
> Please assign it to me. @namansharma3007

Please don't add telephone 📞😂

**Comment by Riddhi050803** [comment]
> > Please assign it to me. @namansharma3007
> 
> Please don't add telephone 📞😂

Then should i add any other image or just a contact form in the middle of the page?

**Comment by namansharma3007** [comment]
> > > Please assign it to me. @namansharma3007
> > 
> > 
> > Please don't add telephone 📞😂
> 
> Then should i add any other image or just a contact form in the middle of the page?

Only contact form
