### ISSUE TITLE
Migrating the database to prisma

### ISSUE THREAD

**Issue by unknown91tech** [namansharma3007/PollQ#41]
@namansharma3007 will create a prisma schema which would be easier to store and run the project locally

Can you assign this issue to me? @namansharma3007

**Comment by namansharma3007** [comment]
@unknown91tech done

**Comment by namansharma3007** [comment]
@unknown91tech Please change the same in Readme.md file

**Comment by unknown91tech** [comment]
@namansharma3007 I tried but wasn't able to successfully migrate the whole backend to prisma using postgres . It was giving ,e several error.

@namansharma3007  It is ok if I close this issue??

And maybe I can work on some other issue.

**Comment by unknown91tech** [comment]
@namansharma3007 Can create a Docker file for this project that would help for the smoother run of the project locally

**Comment by namansharma3007** [comment]
@unknown91tech Please create one 🚀

**Comment by unknown91tech** [comment]
So can I close this issue

**Comment by namansharma3007** [comment]
Please close it
