### ISSUE TITLE
Feature: Develop Login, Signup and Forget password pages. Multiple Developers Required.

### ISSUE THREAD

**Issue by namansharma3007** [namansharma3007/PollQ#7]
#### Develop:
   - Login page
   - Signup page
   - Forget password page

 **Use your creativity for development** 🧠

**Let's make it a big one** 🚀

**Comment by Karan1962** [comment]
@namansharma3007 I would like to work on it . can you please assign me this issue.

**Comment by namansharma3007** [comment]
@Karan1962 
Mission has begun 🚀

**Comment by Rossville** [comment]
@namansharma3007 Can you please assign this issue to me.

**Comment by namansharma3007** [comment]
> @namansharma3007 Can you please assign this issue to me.

@Rossville Done!
Now start the mission 🚀
